Add build option CGO_ENABLED=0
bdd/runitor pull request #20
Opened 2021-04-08 12:20 UTC by t-yag

Adds option for CGO_ENABLED=0. 
It would be nice to be able to run the runitor command in various environments such as alpine.

2021-04-09 01:51 UTC, bdd requested changes

2021-04-09 06:34 UTC, closed without merging

2021-04-10 23:51 UTC, t-yag commented
Thank you for your support.
We want to use this wonderful tool on many platforms.
#21 was wrong, so please ignore it.

Thank you!

2021-04-10 23:51 UTC, t-yag commented on scripts/build
> +  CGO_ENABLED=0 ${GO} build -o "${BUILD_DIR}/" ./cmd/${name}
Thank you for your support.
We want to use this wonderful tool on many platforms.
#21 was wrong, so please ignore it.

Thank you!

2021-04-10 23:52 UTC, t-yag commented
Thank you for your support.
We want to use this wonderful tool on many platforms.
#21 was wrong, so please ignore it.

Thank you!

2021-04-12 02:55 UTC, bdd commented
@t-yag new build with statically linked linux-amd64: https://github.com/bdd/runitor/releases/tag/v0.7.2%2Bbuild-cgo_disabled

2021-04-12 03:16 UTC, t-yag commented
Thank you for quick response. I will use it immediately!