Resend body on 307 redirect
bdd/runitor pull request #80
Opened 2022-11-29 11:34 UTC by apeschar

Before this change, 307 redirects cause errors:

~~~
--- FAIL: TestResubmitRingBufferBody (0.00s)
    api_test.go:361: ping failed: nonretriable error response: 307 Temporary Redirect
~~~

After this change, they work as intended.

Closes #79.

2022-11-29 16:42 UTC, bdd requested changes

2022-11-29 16:54 UTC, apeschar commented on internal/api.go
> +		body = bytes.NewReader(rb.Snapshot())
Sorry, missed that.

I've made sure the unit test catches this potential bug.

2022-11-29 16:56 UTC, apeschar commented on internal/api_test.go
> +		if r.URL.Path == "/redirect-target" {
Retaining the query string would be the servers' responsibility. The client _should not_ append the original query string to the redirect URI returned by the server.

So an example Nginx config should look like this:

~~~
location / {
  return 307 https://hc-ping.com$uri$is_args$args;
};
~~~

2022-11-29 16:57 UTC, apeschar commented on internal/ringbuffer.go
> +// Snapshot returns a clone of r.buf.
Done.

2022-11-29 16:57 UTC, apeschar commented on internal/api_test.go
> +		if string(reqBody) != string(body) {
Thanks! My first Go PR. :)

2022-11-29 17:03 UTC, bdd commented on internal/api.go
> +		body = bytes.NewReader(rb.Snapshot())
I don't think you should unit test Ring Buffer's implementation correctness (which is tested by its own unit tests) again in here. Do you foresee a possible implementation misuse after `Snapshot` gets unexported, soon?

2022-11-29 17:14 UTC, apeschar commented on internal/api.go
> +		body = bytes.NewReader(rb.Snapshot())
I've reverted that part of the test.

> Do you foresee a possible implementation misuse after Snapshot gets unexported, soon?

No.

2022-11-29 17:15 UTC, bdd approved these changes
Thank you for your contribution.

2022-11-29 17:31 UTC, bdd commented
I'll squash and merge these later today.
Will cut a beta release.
Probably will make at least one non-functional change (move of white-box testing into `internal` and not exporting `Snapshot`) 
Hoping to have the v1.2.0 released by this weekend.

2022-12-01 00:12 UTC, bdd commented
c2cea80bba0837ebd372a94facbadb2d4e18d26c

2022-12-01 00:12 UTC, closed without merging